# Generated by Django 3.0.4 on 2020-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=50)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('cap', models.IntegerField()),
                ('state', models.CharField(max_length=5)),
            ],
        ),
    ]
