# Generated by Django 3.0.4 on 2020-03-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0002_auto_20200315_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='hostname',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
