# Generated by Django 3.0.4 on 2020-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0003_auto_20200315_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='dc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='dept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='env',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='cap',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='cpu',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='memory',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
