# Generated by Django 3.0.4 on 2020-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0004_auto_20200319_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardware_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=10)),
                ('cpu', models.CharField(max_length=5)),
                ('memory', models.CharField(max_length=5)),
                ('capacity', models.CharField(max_length=5)),
            ],
        ),
    ]
