# Generated by Django 3.0.4 on 2020-04-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0005_hardware_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
