# Generated by Django 3.0.4 on 2020-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0006_auto_20200422_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='env',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
