# Generated by Django 3.0.4 on 2020-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0007_auto_20200422_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
