# Generated by Django 3.0.4 on 2020-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ippool_web', '0008_cmdb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmdb',
            old_name='state',
            new_name='is_got_ip',
        ),
        migrations.AddField(
            model_name='cmdb',
            name='is_set_vlan',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
